# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b951bed1e29cafc8782822f9ee5657ebcbf492ce76e9f418cc5e8fd33a8a5c1458a47ee61f042593d256d8c41a9ac84e4646b86a224fbb94209f024949eff80

test:
  secret_key_base: 626780647d5d18a989bf434f6baac873d04f0fbfc2811c08a6031c5541156a49d3ca111a21fc66c9bdc6da42b3f848d4e5bc83c73b42de58dd846e4d651b4a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
